### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by nshram** [MuTsunTsai/fen-tool#1]
Hello!
A really great implementation!
I didn't understand this in the Readme: "... it cannot generate a URL that represents an image like some other FEN tools".
The "Copy embed HTML code" seems to do the same function (create URL for image)?
Some features I hope you'll implement soon:
1) Flexible board sizes from 1x1 to mxn (currently only allows 8x8).
2) Optional additional border (consisting of one white and one black strip).

Thank you.

**Comment by nshram** [comment]
Thank you for your replies!

>>> What it means is that most FEN image generating APIs will directly emit a png content...
Embedding for both Joost's and janko.at's PHP generators and your fen-tool works identically for me.

>>> Update: SDK mode is released now.
Great! But I'm still not at a level that I can use it. ;-)

>>> I probably won't support mxn FFEN notation...
mxn boards of sizes less than or greater than 8x8 are not common, but they do exist and the option to show them would be useful. Here's the output from Joost's PHP generator for a 5x3 board: 
https://www.chessproblems.ca/diagrams/image.php?ff=kqrbn%2F5%2FKQRBN&sb=bnc&g=&lc=&gl=&ssq=&bt=

>>> I can, however, clip the drawing to just mxn area as long as m and n are at most 8. Would that be good enough?
Bigger boards would still be nice. Here's a 11x11 board from the PHP generator at janko.at:
https://www.janko.at/Retros/d.php?ff=3*2r3*3N3/*3n6*2r3/*3N*2bp3*2bQ3/2*2b*2r3p3/1*2r2P1p4/4N4p1/1K*3n5p2/3*3Np1B1P2/3pN1p4/3B*2rkb2*3nR/6*3rbN2

>>> Since I already have 1px black line border, do you mean 1px black + 1px white + 1px black?
See the extra border in the 5x3 board above. It has 1px black + 2px white + 3px black which looks good.
The second 11x11 board from janko.at has a single border of 4px, which is less satisfactory.

>>> Alternatively, you could apply CSS to the generated HTML code to obtain all kinds of border you like, but that could also be a bit less user-friendly for some
For me too! ;-)

**Comment by MuTsunTsai** [comment]
OK, I will try support board of any dimension then. It won't be easy though, especially with the consideration of UI and RWD. As for the syntax conflict, now that I think about it, as long as you define the dimension ahead of time, it shouldn't be a problem.

For the border, I think I can provide a simple syntax that allows you to customize it. It will basically be numbers alternating between black pixels and white pixels. For example, `1` will be the default value of 1px black, and `1,2,3` will be the border in your example. How about that?

**Comment by nshram** [comment]
Looks good. Thank you!
Your 123 syntax for borders is also fine.

**Comment by MuTsunTsai** [comment]
![image](https://github.com/MuTsunTsai/fen-tool/assets/39870664/07f4b288-0370-4955-abf2-5a26dd6fa1bf)

Alright, here you go. I'll work on customizable dimension some other time.

**Comment by nshram** [comment]
> The HTML code doesn't give you a png, but an embedded webpage instead.
>> I find that after I paste the HTML code into the web page, the _<iframe src= . . . . style="border:none;width:220px;height:220px"></iframe>_ portion gets stripped out.

**Comment by MuTsunTsai** [comment]
@nshram Depends on the environment, that is perfectly possible, as some of the environments forbid the usage of iframes. If you really need something that is allowed in practically all environments, you can go with “base64 link” button. You will get a really long text, and you then write
```
<img src="(base64 link here)">
```
This always works. The only downside is that the link is REALLY long.

**Comment by MuTsunTsai** [comment]
@nshram Customizable board dimension in on now. Please try it.

**Comment by nshram** [comment]
![board (2)](https://github.com/MuTsunTsai/fen-tool/assets/1410068/0f6ebca6-60cd-447c-981a-a3814ac03ece)

**Comment by nshram** [comment]
![board (3)](https://github.com/MuTsunTsai/fen-tool/assets/1410068/466e06bd-aebd-4641-9e3c-e7ca51c8dd00)

**Comment by MuTsunTsai** [comment]
@nshram Glad you like it. Don't forget to star the project! Also, if you still have difficulties with SDK or iframe embedding, feel free to show me your website and I'll help you figure it out.

**Comment by nshram** [comment]
Starred!
