### ISSUE TITLE
Faulty solution animation of problems using new condition seriescapture

### ISSUE THREAD

**Issue by nshram** [MuTsunTsai/fen-tool#10]
Example:
8/8/8/8/2K5/1pnp4/p7/k7
sti =1
cond seriescapture

Popeye wasm-32Bit v4.89 (512 MB)

   

```
1.Kc4*b3*c3*d3-c2 = !

1.Kc4*d3*c3*b3-c2 = !

```
solution finished. Time = 0.020 s

I think this is due to spaces being present before or after the "*" in the solution.

**Comment by MuTsunTsai** [comment]
I think this syntax was just introduced in 4.89. Added the support just now.
