### ISSUE TITLE
Pawn promotions in the helpmate

### ISSUE THREAD

**Issue by AyatsujiP** [MuTsunTsai/fen-tool#11]
Position: K7/1P5R/b1kr4/rpp1b3/8/8/6pq/8 (PDB P0500540)
https://mutsuntsai.github.io/fen-tool/?fen=K7%2F1P5R%2Fb1kr4%2Frpp1b3%2F8%2F8%2F6pq%2F8

===
Stipulation H#2
===
Solution:
  1.Kc6-b6 b7-b8=B   2.Rd6-c6 Bb8-a7 #
  1.Rd6-d5 b7-b8=R   2.Kc6-d6 Rb8-b6 #
  1.Rd6-d7 Rh7-h6 +   2.Kc6-c7 b7-b8=Q #
  1.Rd6-e6 b7-b8=S +   2.Kc6-d6 Rh7-d7 #
===

The issue:
In the Playing Mode, 1...b7-b8=B (or similar promotions) is shown as the promotion to the Black bishop, not to the White bishop.

**Comment by MuTsunTsai** [comment]
https://github.com/MuTsunTsai/fen-tool/assets/39870664/5eb8b405-1741-4dcf-8bd5-8f345222d3a2

I couldn't reproduce the issue. Is this how you operated it?

It also seems to work fine if you setup the position, enter manual playing mode (with Black's turn), and paste the moves from one of the solutions.

**Comment by AyatsujiP** [comment]
Thank you, that is what I operated. I have attached the video.
This video is captured on Firefox 116.0.3 (private browsing mode) on Windows 10.

https://github.com/MuTsunTsai/fen-tool/assets/8664452/5c598e6c-caef-495f-91b1-2808faab40ee

**Comment by MuTsunTsai** [comment]
Fixed. Turns out that the cause is that it fails to consider the possibility of capitalized "H#2" as stip! It should work now.
