### ISSUE TITLE
After updates of 2-Jun-23, Gray and White background for squares not working

### ISSUE THREAD

**Issue by nshram** [MuTsunTsai/fen-tool#2]
It's still showing the default orange colours.
<iframe src="https://mutsuntsai.github.io/fen-tool/gen/?fen=rsbqkbsr/pppppppp/8/8/8/8/PPPPPPPP/RSBQKBSR&size=26&bg=grayblackWhite&knightOffset=0.625" style="border:none;width:210px;height:210px"></iframe>

The "Save Image" button generates a board with Gray and White squares correctly.

**Comment by MuTsunTsai** [comment]
Oops! Thanks for reporting! It's fixed now; the correct code should have been
```html
<iframe src="https://mutsuntsai.github.io/fen-tool/gen/?fen=rsbqkbsr/pppppppp/8/8/8/8/PPPPPPPP/RSBQKBSR&size=26&bg=gray&blackWhite&knightOffset=0.625" style="border:none;width:210px;height:210px"></iframe>
```
You might need to refresh the page a few times for the update to take effect.

**Comment by nshram** [comment]
Thanks!
