### ISSUE TITLE
Position is not reset to the original one after the helpmate solution is played

### ISSUE THREAD

**Issue by petkopuma** [MuTsunTsai/fen-tool#5]
When playing the solutions of helpmate with multiple solutions reset the position before playing another solution.

**Comment by MuTsunTsai** [comment]
That's a great suggestion! Indeed right now the initial position can only be found in the "beginning" button, which is rather inconvenient. I've changed it to having the initial position before every solution (in the new `*` button). Please try it!
Note: you may need to refresh the page a few times to see the update.
