### ISSUE TITLE
Use left/right halves of the board for playing through the solution

### ISSUE THREAD

**Issue by nshram** [MuTsunTsai/fen-tool#6]
This is the feature in Turevski's py2web!

**Comment by MuTsunTsai** [comment]
I was aware of that, but didn't plan to implement it considering that it will be a feature available only in Popeye solution playing mode, which is somewhat inconsistent in UI design. Yet now that I think about it I don't think it would be bad for UX either, so I just implemented it and it's on now.

**Comment by nshram** [comment]
Works fine.
Thank you again!
