### ISSUE TITLE
.olv file support!

### ISSUE THREAD

**Issue by nshram** [MuTsunTsai/fen-tool#7]
Feature request:
Read and write .olv files (of Turevski's Olive program).
Need not fill all the fields used by Olive (like name, source, date, distinction, etc.). 
Even leaving all blank should work.
Only position (and Popeye options) should be enough.

**Comment by MuTsunTsai** [comment]
Sounds like a great idea! Though I will have to postpone working on adding new features until perhaps later this year, as I have other urgent projects at hand.

**Comment by nshram** [comment]
That's fine. You've already done in a few months what others would've taken years! ;-)

**Comment by MuTsunTsai** [comment]
@nshram Hi and thanks for the long waiting! Olive format support is now added. To use it, open the .olv file from the project page. Try it!

**Comment by nshram** [comment]
I saved this position in Olive: WKc2, WPg7, BKa1, gave stipulation as #2, and select option try. Option variation is pre-selected.
Then opened the generated .olv file in fen-tool.
Trying to run  gives error. The option "Try" is being included in the option condition.
Don't know whether this is a bug in Olive or in fen-tool.

**Comment by MuTsunTsai** [comment]
@nshram Well, that part of the source code is directly copied from that of Olive, but looks like it's incomplete somehow. I have correct it based on Popeye's documentation. See if it's good now.

**Comment by nshram** [comment]
Yes. Works ok now.

**Comment by MuTsunTsai** [comment]
@nshram OK, I've done some work to improve fairy piece support with Olive. See if it's better now.

**Comment by nshram** [comment]
Great! It's able to open all the dozen or so .olv files with fairy pieces I threw at it, without giving that mapping error message. The parsing was also correct, as Popeye WASM gave the solutions without any errors.
Fen-tool is even more a must-have for any chess problem enthusiast!
