### ISSUE TITLE
Changed FEN parameters after playing

### ISSUE THREAD

**Issue by viktpal** [MuTsunTsai/fen-tool#9]
The playing mode changes the FEN parameters (turn, half-moves, full-moves), which remain even after pasting a new position or manually editing it. This is very annoying.

**Comment by MuTsunTsai** [comment]
I think I can agree with that. I've changed the behavior so that exiting playing mode will reset the position (just like Popeye solution mode). In case any one prefer the old behavior, I can make that an option later, but let's try it for the moment.

**Comment by viktpal** [comment]
The position is not always reset. If the user selects a position in playing mode and analyzes this new position, the changed parameters remain after exiting playing mode.

**Comment by MuTsunTsai** [comment]
By “reset on exiting” I mean to reset the position and parameters to the same state when one entered the playing, not to reset the parameters to those of the initial game array. The latter behavior will not make sense in general, and when needed, there is a button for that.

**Comment by viktpal** [comment]
What is the logic in that a pasted or manually entered new position has the parameters of some previously analyzed position (e.g.,  "b - - 6 7")? I think it should be default parameters "w - - 0 1". The "Reset settings" button changes the parameters to "w KQkq - 0 1", which is not suitable for most positions, since castling is usually not possible in them.

**Comment by MuTsunTsai** [comment]
The logic is that when the parameters are not given in the pasted position, it simply couldn't know what is intended and therefore the best it can do is to do nothing. Why should it assume that the pasted position must be White's move? And why should it reset the paramters on every manual editing? I can easily imagine that would be equally annoying to many users, who might just want to make slight modifications on their working positions.

For the reset button, you don't need to worry about the castling states. When it enters the playing mode, it automatically checks if those state make sense and discard those that don't.
